name: books_store


services:
  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    image: nginx-${COMPOSE_PROJECT_NAME}
    container_name: nginx-${COMPOSE_PROJECT_NAME}
    env_file: .env
    environment:
      RUNNING_INSIDE_DOCKER: 1
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    networks:
      - alchemy_net
    restart: ${DOCKER_CONTAINERS_RESTART}
    develop:
      watch:
        - action: rebuild
          path: ./nginx


  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile
    image: gateway-${COMPOSE_PROJECT_NAME}
    container_name: gateway-${COMPOSE_PROJECT_NAME}
    env_file: .env
    environment:
      RUNNING_INSIDE_DOCKER: 1
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    networks:
      - alchemy_net
    restart: ${DOCKER_CONTAINERS_RESTART}
    develop:
      watch:
        - action: rebuild
          path: ./gateway


  authorizer:
    build:
      context: ./authorizer
      dockerfile: dockerfile
    image: authorizer-${COMPOSE_PROJECT_NAME}
    container_name: authorizer-${COMPOSE_PROJECT_NAME}
    env_file: .env
    environment:
      RUNNING_INSIDE_DOCKER: 1
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${AUTHORIZER_PORT}:${AUTHORIZER_PORT}"
    networks:
      - alchemy_net
    restart: ${DOCKER_CONTAINERS_RESTART}
    develop:
      watch:
        - action: rebuild
          path: ./

          
  # server:
  #   build:
  #     context: ./server
  #     dockerfile: dockerfile
  #   image: server-${COMPOSE_PROJECT_NAME}
  #   container_name: server-${COMPOSE_PROJECT_NAME}
  #   env_file: .env
  #   environment:
  #     RUNNING_INSIDE_DOCKER: 1
  #     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
  #   ports:
  #     - "${SERVER_PORT}:${SERVER_PORT}"
  #   networks:
  #     - alchemy_net
  #   restart: ${DOCKER_CONTAINERS_RESTART}
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./


  valkey:
    build:
      context: ./valkey
      dockerfile: dockerfile
    image: valkey-${COMPOSE_PROJECT_NAME}
    container_name: valkey-${COMPOSE_PROJECT_NAME}
    env_file: .env
    environment:
      RUNNING_INSIDE_DOCKER: 1
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${VALKEY_PORT}:${VALKEY_PORT}"
    networks:
      - alchemy_net
    volumes:
      - ./valkey-data:/var/lib/valkey/data
    restart: ${DOCKER_CONTAINERS_RESTART}
    develop:
      watch:
        - action: rebuild
          path: ./


  postgres:
    build:
      context: ./postgres
      dockerfile: dockerfile
    image: postgres-${COMPOSE_PROJECT_NAME}
    container_name: postgres-${COMPOSE_PROJECT_NAME}
    env_file: .env
    environment:
      RUNNING_INSIDE_DOCKER: 1
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - alchemy_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: ${DOCKER_CONTAINERS_RESTART}
    develop:
      watch:
        - action: rebuild
          path: ./


networks:
  alchemy_net:
    driver: bridge
    name: alchemy_net
