name: alchemy


services:
  main:
    build:
      context: ./main
      dockerfile: dockerfile
    image: main
    container_name: main
    env_file: .env
    environment:
      RUNNING_INSIDE_DOCKER: 1
    ports:
      - "${MAIN_PORT}:${MAIN_PORT}"
    networks:
      - alchemy_net
    restart: ${DOCKER_CONTAINERS_RESTART}


  postgres:
    build:
      context: ./postgres
      dockerfile: dockerfile
    image: postgres-alchemy
    container_name: postgres-alchemy
    env_file: .env
    environment:
      RUNNING_INSIDE_DOCKER: 1
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - alchemy_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: ${DOCKER_CONTAINERS_RESTART}


volumes:
  postgres_data:
    driver: local

networks:
  alchemy_net:
    driver: bridge
    name: alchemy_net
