FROM nginx:1.25-alpine


RUN apk update && apk add --no-cache gettext bash && rm -rf /var/cache/apk/*

COPY init-scripts /init-scripts

RUN chmod +x /init-scripts/entrypoint.sh

ENTRYPOINT ["/init-scripts/entrypoint.sh"]