"""empty message

Revision ID: d288ffc7c3b6
Revises: 
Create Date: 2025-08-08 03:14:35.920398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src.services.db.models.base_model import UserRole

# revision identifiers, used by Alembic.
revision: str = 'd288ffc7c3b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



user_role_enum = postgresql.ENUM(
    'user', 'admin', 'seller',
    name='role'
)


def upgrade() -> None:
    user_role_enum.create(op.get_bind(), checkfirst=True)

    # 3) добавляем новую колонку на основе этого типа
    op.add_column(
        'users',
        sa.Column(
            'role',
            user_role_enum,
            nullable=False,
            server_default='user'
        )
    )

    # 5) удаляем старую колонку role
    op.drop_column('users', 'user_role')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('user', 'admin', 'seller', name='role'), server_default=sa.text("'user'::user_role"), autoincrement=False, nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('users', 'user_role')
    # ### end Alembic commands ###
